# Data Preprocessing

In [2]:
# Kumpulan Library Yang Diperlukan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Cleaninng Text
import re
import string
import nltk
from nltk.corpus import stopwords

In [3]:
# Load dataset
# Ganti 'nama_file.csv' sesuai dengan file yang kamu download
df_True = pd.read_csv('True.csv')
df_Fake = pd.read_csv('Fake.csv')

# Intip data teratas
print("Data Berita Asli:")
display(df_True.head())

print("\nData Berita Palsu:")
display(df_Fake.head())

# Ngecek data
print(df_True.info())
print(df_Fake.info())

# Cek data kosong
print("Missing values in True News:", df_True.isnull().sum().sum())
print("Missing values in Fake News:", df_Fake.isnull().sum().sum())

# Cek data duplikat
print("Duplicate rows in True News:", df_True.duplicated().sum())
print("Duplicate rows in Fake News:", df_Fake.duplicated().sum())

# print("Kategori Berita Asli:")
# print(df_True['subject'].value_counts())

# print("\nKategori Berita Palsu:")
# print(df_Fake['subject'].value_counts())

# # Contoh cek panjang karakter di judul
# df_True['title_len'] = df_True['title'].apply(len)
# print("Rata-rata panjang judul berita asli:", df_True['title_len'].mean())

# df_Fake['title_len'] = df_Fake['title'].apply(len)
# print("Rata-rata panjang judul berita palsu:", df_Fake['title_len'].mean())

Data Berita Asli:

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

Data Berita Palsu:

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

<class 'pandas.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  str
 1   text     21417 non-null  str
 2   subject  21417 non-null  str
 3   date     21417 non-null  str
dtypes: str(4)
memory usage: 669.4 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  str
 1   text     23481 non-null  str
 2   subject  23481 non-null  str
 3   date     23481 non-null  str
dtypes: str(4)
memory usage: 733.9 KB
None
Missing values in True News: 0
Missing values in Fake News: 0
Duplicate rows in True News: 206
Duplicate rows in Fake News: 3

In [4]:
# 1. Pelabelan Data
df_True['label'] = 1
df_Fake['label'] = 0

# 2. Proses Gabungin Data
df = pd.concat([df_True, df_Fake], axis=0).reset_index(drop=True)

# 3. Pembersihan Dasar
df.drop(['date', 'subject'], axis=1, inplace=True, errors='ignore')
df['full_text'] = df['title'] + " " + df['text']

# 4. Verifikasi Akhir untuk Validasi
print(f"Jumlah Kolom Sekarang: {df.shape[1]}") # Seharusnya minimal 4 (title, text, full_text, label)
print(df['label'].value_counts()) # Untuk memastikan label 1 dan 0 sudah ada
df.info()

Jumlah Kolom Sekarang: 4
label
0    23481
1    21417
Name: count, dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      44898 non-null  str
 1   text       44898 non-null  str
 2   label      44898 non-null  int64
 3   full_text  44898 non-null  str
dtypes: int64(1), str(3)
memory usage: 1.4 MB

In [5]:
# Hapus data yang duplikat - Pembersihan Data
df.drop_duplicates(inplace=True)

In [6]:
# Nampilin data yang udah dibersihin
print("Struktur Data Terbaru:")
display(df.head())

print(f"Jumlah Baris Akhir: {df.shape[0]}")
print(f"Jumlah Kolom Akhir: {df.shape[1]}")

print("Jumlah Duplikat Tersisa:", df.duplicated().sum())

df.info()

Struktur Data Terbaru:

,title,text,label,full_text
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,1,"As U.S. budget fight looms, Republicans flip t..."
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,1,U.S. military to accept transgender recruits o...
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,1,Senior U.S. Republican senator: 'Let Mr. Muell...
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,1,FBI Russia probe helped by Australian diplomat...
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,1,Trump wants Postal Service to charge 'much mor...

Jumlah Baris Akhir: 39105
Jumlah Kolom Akhir: 4
Jumlah Duplikat Tersisa: 0
<class 'pandas.DataFrame'>
Index: 39105 entries, 0 to 44119
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      39105 non-null  str
 1   text       39105 non-null  str
 2   label      39105 non-null  int64
 3   full_text  39105 non-null  str
dtypes: int64(1), str(3)
memory usage: 1.5 MB

In [7]:
# Cleaning Text
# 1. Download daftar kata umum (hanya perlu sekali)
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# 2. Definisikan fungsi pembersih teks
def clean_text(text):
    # Mengubah ke huruf kecil semua
    text = text.lower()
    # Menghapus teks di dalam kurung (info redaksi/pengirim)
    text = re.sub('\[.*?\]', '', text)
    # Menghapus tanda baca
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    # Menghapus kata yang mengandung angka
    text = re.sub('\w*\d\w*', '', text)     
    # Menghapus kata-kata tidak bermakna (stopwords)
    text = " ".join([word for word in text.split() if word not in stop_words])
    return text

# 3. Terapkan fungsi ke dataframe untuk membuat kolom baru
print("Processing Text")
df['clean_text'] = df['full_text'].apply(clean_text)
print("Selesai! Kolom 'clean_text' sekarang sudah siap.")

# Cek 5 baris pertama untuk memastikan kolomnya muncul
df[['full_text', 'clean_text']].head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Processing Text
Selesai! Kolom 'clean_text' sekarang sudah siap.

,full_text,clean_text
0,"As U.S. budget fight looms, Republicans flip t...",us budget fight looms republicans flip fiscal ...
1,U.S. military to accept transgender recruits o...,us military accept transgender recruits monday...
2,Senior U.S. Republican senator: 'Let Mr. Muell...,senior us republican senator let mr mueller jo...
3,FBI Russia probe helped by Australian diplomat...,fbi russia probe helped australian diplomat ti...
4,Trump wants Postal Service to charge 'much mor...,trump wants postal service charge much amazon ...

# Feature Extraction & Model Training

In [1]:
# Kumpulan Library Yang Diperlukan untuk FE dan MT
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import pickle # Untuk simpan model nanti
import time
import sys

In [8]:
# Data Splitting
# 1. Tentukan Fitur (X) dan Target (y)
X = df['clean_text']
y = df['label']

# 2. Bagi data (80% Training, 20% Testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Data Training: {len(X_train)} baris")
print(f"Data Testing: {len(X_test)} baris")

Data Training: 31284 baris
Data Testing: 7821 baris

In [ ]:
from sklearn.pipeline import Pipeline

# 3. Membangun Automated Pipeline
# Ini menggabungkan TF-IDF dan Logistic Regression jadi satu "ban berjalan"
pipeline_model = Pipeline([
    ('tfidf', TfidfVectorizer(max_features=5000)),
    ('model', LogisticRegression())
])

print("Training Logistic Regression...")
start_time_lr = time.time()
pipeline_model.fit(X_train, y_train) # Pipeline otomatis melakukan fit_transform pada data training
time_lr = time.time() - start_time_lr
predictions_lr = pipeline_model.predict(X_test)

#4. Random Forest Model
rf_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(max_features=5000)),
    ('model', RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1))
])

print("Training Random Forest... ")
start_time_rf = time.time()
rf_pipeline.fit(X_train, y_train) # Pipeline otomatis melakukan fit_transform pada data training
time_rf = time.time() - start_time_rf
predictions_rf = rf_pipeline.predict(X_test)

# 5. Cek Hasil Akurasi & Evaluasi
print("1. HASIL: LOGISTIC REGRESSION")
print(f"Waktu Training : {time_lr:.2f} detik")
print(f"Akurasi        : {accuracy_score(y_test, predictions_lr) * 100:.2f}%\n")
print("Classification Report:\n", classification_report(y_test, predictions_lr))

print("2. HASIL: RANDOM FOREST") # Hanya Untuk Perbandingan 2 model
print(f"Waktu Training : {time_rf:.2f} detik")
print(f"Akurasi        : {accuracy_score(y_test, predictions_rf) * 100:.2f}%\n")
print("Classification Report:\n", classification_report(y_test, predictions_rf))

Training Logistic Regression...
Training Random Forest...
1. HASIL: LOGISTIC REGRESSION
Waktu Training : 8.50 detik
Akurasi        : 98.58%

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98      3564
           1       0.98      0.99      0.99      4257

    accuracy                           0.99      7821
   macro avg       0.99      0.99      0.99      7821
weighted avg       0.99      0.99      0.99      7821

2. HASIL: RANDOM FOREST
Waktu Training : 22.66 detik
Akurasi        : 99.59%

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      1.00      3564
           1       0.99      1.00      1.00      4257

    accuracy                           1.00      7821
   macro avg       1.00      1.00      1.00      7821
weighted avg       1.00      1.00      1.00      7821

# Penyimpanan Model dan Vectorizer (Penerjemah Angka)

In [10]:
import pickle

# Simpan Pipeline utuh (isinya sudah ada TF-IDF + Model)
with open('pipeline_fake_news.pkl', 'wb') as f:
    pickle.dump(pipeline_model, f)

print("Pipeline berhasil disimpan! File ini yang nanti akan dipasang di Flask.")

print("Model dan Vectorizer berhasil diamankan! Siap lanjut ke Flask API.")

Pipeline berhasil disimpan! File ini yang nanti akan dipasang di Flask.
Model dan Vectorizer berhasil diamankan! Siap lanjut ke Flask API.